name: vrhaman
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_calendar_kit: ^0.0.1+1
  flutter_image_slideshow: ^0.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  fpdart: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  hugeicons: ^0.0.7
  image_picker: ^1.1.2
  location: ^7.0.1
  lottie: ^3.1.3
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  timeago: ^3.7.0
  firebase_auth: ^5.4.0
  otpless_flutter: ^2.2.2
  photo_view: ^0.15.0
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.1
  socket_io_client: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  rating_bar_updated: ^0.2.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  max_sdk_android: 33
  remove_alpha_ios: true
